language: python

python:
  - "3.7"

script:
  - python sort.py
  - cp README.md docs/index.md
  - mkdocs build

deploy:
  provider: pages
  local-dir: site
  skip-cleanup: ton
  keep-history: ton
  github-token: $GITHUB_TOKEN
  on:
    branch: master
